global proc shelf_THIAGO () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;
	  separator
        -enable 1
        -width 34
        -height 35
        -manage 1
        -visible 1
        -preventOverride 0
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -style "shelf" 
        -horizontal 0
    ;
} 
